version: '3.9'
services:
  app:
    build: .
    container_name: lancet_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: lancet_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: lancet_db
    restart: always
    environment:
      MYSQL_DATABASE: lancet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
